ami_id              = "ami-0c02fb55956c7d316"
instance_types      = ["t2.micro", "t2.micro", "t2.micro"]
key_name            = "jenkins-agent-key"
public_key_path     = "./id_rsa.pub"
region              = "us-east-1"
server_count        = 3
server_names        = ["Jenkins-Master", "Jenkins-Agent-1", "Jenkins-Agent-2"]
environments        = ["jenkins", "jenkins", "jenkins"]
server_ports        = [[8080, 22, 50000], [22, 50000], [22, 50000]]
allowed_cidr_blocks = ["0.0.0.0/0"]
associate_public_ip = true
enable_elastic_ip   = true
install_jenkins     = false