ami_id              = "ami-02d26659fd82cf299"
instance_types      = ["t2.micro"]
key_name            = "jenkins-master-key"
public_key_path     = "./id_rsa.pub"
region              = "ap-south-1"
server_count        = 1
server_names        = ["Jenkins-Master"]
environments        = ["Dev"]
server_ports        = [[8080, 22, 50000]]
allowed_cidr_blocks = ["0.0.0.0/0"]
associate_public_ip = true
enable_elastic_ip   = true
install_jenkins     = true